# -*- coding: utf-8 -*-
"""Copy of CandidAI NLP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-_m9KJ-IqKH0E9ZYd6voDf1bcHlQIDU_

# A Natural Language Processing approach to filtering hate speech in LLM prompts


Group 2 plans to use Media Bias data set to train a NLP model, in detecting biases, such as hate speech or racial bias, focusing more on positive words that are presented in negative contexts, such as sarcasm. And apply that model with LLM prompts dataset.
The aim of the project is to enter deeper into human minds during their interaction with AI models, allowing for a candid understanding of how they communicate and perceive the world around them, as well as glimpses into their mental health.
This model, in the future, hopes to kick start  AI models, especially mental health ai models to approach human prompts with better understanding and different healthier responses.


### Group Members

Varnika, Kaavya Lakshmi, V Venkatesh, Chacko C



### Datasets

Media Bias: https://github.com/Media-Bias-Group/MBIB/blob/main/README.md

@inproceedings{Wessel2023,
title = {Introducing MBIB - the first Media Bias Identification Benchmark Task and Dataset Collection},
author = {Martin Wessel and Tomas Horych and Terry Ruas and Akiko Aizawa and Bela Gipp and Timo Spinde},
url = {https://media-bias-research.org/wp-content/uploads/2023/04/Wessel2023Preprint.pdf
},
doi = {https://doi.org/10.1145/3539618.3591882},
isbn = {978-1-4503-9408-6/23/07},
year = {2023},
date = {2023-07-01},
urldate = {2023-07-01},
booktitle = {Proceedings of the 46th International ACM SIGIR Conference on Research and Development in Information Retrieval (SIGIR ’23)},
publisher = {ACM},
address = {New York, NY, USA},


Prompts: https://huggingface.co/datasets/data-is-better-together/10k_prompts_ranked
"""

!pip install datasets transformers torch scikit-learn

from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
from transformers import TrainingArguments, Trainer
import torch
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

from datasets import load_dataset, concatenate_datasets
import random

dataset_dict = load_dataset("mediabiasgroup/mbib-base")
hate_dataset=dataset_dict['hate_speech']
racial_dataset=dataset_dict['racial_bias']

hate_dataset

racial_dataset

def relabel_hate(example):
    example['label'] = 1 if example['label'] == 1 else 0
    return example

def relabel_racial(example):
    example['label'] = 2 if example['label'] == 1 else 0
    return example

hate_relabeled = hate_dataset.map(relabel_hate)
racial_relabeled = racial_dataset.map(relabel_racial)

import re
import string
import warnings
warnings.filterwarnings("ignore")

def clean_text(text):
  if text is None: return ""
  text = str(text).lower()
  text = re.sub(r'<[^>]*>', '', text)
  text = re.sub(r'http\S+|www\S+', '', text)
  text = text.translate(str.maketrans('', '', string.punctuation))
  text = re.sub(r'\d+', '', text)
  text = re.sub(r'\s+', ' ', text).strip()
  return text

combined_dataset = concatenate_datasets([hate_relabeled, racial_relabeled])

split_dataset = combined_dataset.train_test_split(test_size=0.2, seed=42)

train_dataset = split_dataset["train"].shuffle(seed=42).select(range(5000))
test_dataset = split_dataset["test"].shuffle(seed=42).select(range(1000))

model_name="bert-base-uncased"
tokenizer=AutoTokenizer.from_pretrained(model_name)

def tokenize_function(examples):
  return tokenizer(examples["text"], padding="max_length", truncation=True, max_length=254)

tokenized_train = train_dataset.map(tokenize_function, batched=True)
tokenized_test = test_dataset.map(tokenize_function, batched=True)

tokenized_train.set_format("torch", columns=['input_ids', 'token_type_ids', 'attention_mask', 'label'])
tokenized_test.set_format("torch", columns=['input_ids', 'token_type_ids', 'attention_mask', 'label'])

print(split_dataset)

model=AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=3)

def compute_metrics(pred):
  labels=pred.label_ids
  preds=pred.predictions.argmax(-1)
  precision, recall, f1, _=precision_recall_fscore_support(labels, preds, average="weighted",zero_division=0)
  acc=accuracy_score(labels, preds)
  return{"accuracy":acc, "f1":f1, "precision":precision, "recall":recall}

from transformers import TrainingArguments, Trainer

training_args=TrainingArguments(
    output_dir="./results",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    #evaluation_strategy="epoch",
    logging_strategy="no", #disables logging
    report_to=[], # disables W&B,TensorBoards, etc
)

trainer=Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_test,
    compute_metrics=compute_metrics,
)

trainer.train()

evaluation_results = trainer.evaluate()
print ("Evaluation Metrics:")
print (evaluation_results)

pred_output = trainer.predict(tokenized_test)
pred_logits = pred_output.predictions
pred_labels = pred_logits.argmax(axis=-1)

print(pred_labels[:20])

from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

text = "white people are trash"
inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True)

with torch.no_grad():
    outputs = model(**inputs)

logits = outputs.logits
pred = torch.argmax(logits, dim=1).item()

print("Input Text:", text)
print("Predicted Label ID:", pred)

import torch

# 1. Define the device based on availability (to match the model's device)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Assuming 'tokenizer' is loaded and 'trainer' is available
tuned_model = trainer.model

text = "white people are trash."
inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True)

# 2. CRITICAL FIX: Move the Model and Inputs to the selected device

# Move the model to the device (it might already be there, but this ensures it)
tuned_model = tuned_model.to(device)

# Move the input tensors inside the dictionary to the device
inputs = {k: v.to(device) for k, v in inputs.items()}

# 3. Run prediction using the tuned model
with torch.no_grad():
    outputs = tuned_model(**inputs)

logits = outputs.logits
pred = torch.argmax(logits, dim=1).item()

# Map the numerical ID to your defined class names for clarity
label_map = {0: "Neutral", 1: "Hate Speech", 2: "Racial Bias"}

print("Input Text:", text)
print("Predicted Label ID:", pred)
print("Predicted Class:", label_map.get(pred, "Unknown"))

from datasets import load_dataset

ds = load_dataset("data-is-better-together/10k_prompts_ranked", split="train")

def preprocess_fn(examples):
    return tokenizer(examples["prompt"], truncation=True, padding=True)

tokenized_ds = ds.map(preprocess_fn, batched=True)

pred_results = trainer.predict(tokenized_ds)

import numpy as np

logits = pred_results.predictions
preds = np.argmax(logits, axis=-1)

ds = ds.add_column("predicted_label", preds)
output_filename = "3_class_predictions_on_10k_prompts.csv"
ds.to_csv(output_filename)
print(f"✅ Classification complete. Results saved to {output_filename}")

import pandas as pd
from collections import Counter
import re
import string
import warnings
warnings.filterwarnings("ignore")

# Assuming you have run the inference and have this file saved:
classified_file = "3_class_predictions_on_10k_prompts.csv"

# This code loads the file and filters for biased prompts
df = pd.read_csv(classified_file)

# Filter only for Hate Speech (1) and Racial Bias (2) predictions
biased_df = df[df['predicted_label'].isin([1, 2])].copy()

# Include clean_text function here for self-containment
def clean_text(text):
  if text is None: return ""
  text = str(text).lower()
  text = re.sub(r'<[^>]*>', '', text)
  text = re.sub(r'http\S+|www\S+', '', text)
  text = text.translate(str.maketrans('', '', string.punctuation))
  text = re.sub(r'\d+', '', text)
  text = re.sub(r'\s+', ' ', text).strip()
  return text

final_minimalist_stop_words = set([
    # Pronouns, Conjunctions, Articles, Prepositions (Core Function Words)
    'the', 'a', 'is', 'to', 'and', 'i', 'of', 'it', 'that', 'this', 'be', 'are',
    'in', 'have', 's', 'on', 'with', 'for', 'what', 'as', 'who', 'an', 'not',
    'was', 'by', 'his', 'about', 'we', 'no', 'at', 'he', 'your', 'me', 'can',
    'or', 're', 'from', 'if', 'they', 'do', 'up', 'all', 'my', 'her', 'so', 'has',
    'but', 'where', 'how', 'she', 'get', 'there', 'their', 'one', 'out', 'will',
    'just', 'when', 'him', 'more', 'some', 'two', 'had', 'which', 'other',
    'us', 'only', 'back', 'after', 'tell', 'way', 'does', 'yes', 'over', 'now', 'also',
    'let', 'most', 'true', 'without', 'why', 'you', 'thing', 'being', 'here',
    'something', 'off', 'again', 'look', 'lot', 'come', 'world', 'around', 'take',
    'been', 'please', 'were', 'into', 'any', 'down', 'well', 'am', 'could', 'them',
    'between', 'single', 'given', 'possible', 'same', 'many', 'ever', 'either', 'feel',
    'these', 'see', 'each', 'options', 'even', 'than', 'once', 'getting', 'think',
    'always', 'believe', 'own', 'explain', 'bit', 'day', 'step', 'mean', 'another',
    'trying', 'use', 'data',
])

# Recalculate word counts using the original data structure
def get_word_counts(texts_series):
    all_words = []
    for text in texts_series:
        if isinstance(text, str):
            # Using simple regex for extraction
            all_words.extend(re.findall(r'\b\w+\b', text.lower()))
    return Counter(all_words)

# --- Assuming 'biased_df' is loaded, we recalculate counts for the printout ---
hate_texts = biased_df[biased_df['predicted_label'] == 1]['prompt'].apply(clean_text)
hate_counts = get_word_counts(hate_texts)
racial_texts = biased_df[biased_df['predicted_label'] == 2]['prompt'].apply(clean_text)
racial_counts = get_word_counts(racial_texts)


# 4. Filter the word counts to focus on "Signal Words"
def get_signal_words(counts, stopwords, limit=15):
    signal_words = []
    for word, count in counts.most_common():
        # Exclude numbers and single characters as well
        if word.isdigit() or len(word) < 2:
            continue
        if word not in stopwords:
            signal_words.append((word, count))
            if len(signal_words) >= limit:
                break
    return signal_words


# --- Get the Top 15 Signal Words for Hate Speech (1) (Minimalist Filter) ---
hate_signal = get_signal_words(hate_counts, final_minimalist_stop_words, limit=15)
print("\n--- Top 15 Words Indicating Hate Speech (1) (Minimalist Filter) ---")
for word, count in hate_signal:
    print(f"Hate Speech: {word:<15} (Count: {count})")

# --- Get the Top 15 Signal Words for Racial Bias (2) (Minimalist Filter) ---
racial_signal = get_signal_words(racial_counts, final_minimalist_stop_words, limit=15)
print("\n--- Top 15 Words Indicating Racial Bias (2) (Minimalist Filter) ---")
for word, count in racial_signal:
    print(f"Racial Bias: {word:<15} (Count: {count})")

df = pd.read_csv("3_class_predictions_on_10k_prompts.csv")

import pandas as pd
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer

# Download the vader_lexicon if not already present
nltk.download('vader_lexicon')

# CRITICAL: Initialize SIA inside the execution block
sia = SentimentIntensityAnalyzer()

def find_positive_words_in_bias(text):
    positive_words = []
    if not isinstance(text, str): return "" # Safety check
    words = text.lower().split()

    for word in words:
        # We look for words with a high positive score (close to perfect positivity)
        score = sia.polarity_scores(word)['pos']
        if score > 0.9:
            positive_words.append(word)

    return ", ".join(positive_words)

# --- Load and Filter Data ---
classified_file = "3_class_predictions_on_10k_prompts.csv"
df = pd.read_csv(classified_file)

# Filter for the usable biased prompts (Hate Speech, Label 1)
# We include Label 2 just in case, but results will be dominated by Label 1
biased_df = df[df['predicted_label'].isin([1, 2])].copy()

# --- Apply Sarcasm Detection ---
biased_df['positive_words_in_bias'] = biased_df['prompt'].apply(find_positive_words_in_bias)

# --- Filter for Candidates (Where a strong positive word was found) ---
irony_candidates = biased_df[biased_df['positive_words_in_bias'].str.len() > 0]

print(f"Total Biased Prompts Analyzed: {len(biased_df)}")
print(f"Found {len(irony_candidates)} potential ironic/sarcastic candidates.")

print("\n--- Example Prompts with Positive Words in a Biased Context ---")
# Show the prompt, the predicted bias, and the positive word identified by VADER
print(irony_candidates[['prompt', 'predicted_label', 'positive_words_in_bias']].head(10))

from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def compute_metrics(pred):
  labels = pred.label_ids
  preds = pred.predictions.argmax(-1)

  precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average="weighted")

  acc = accuracy_score(labels, preds)
  return {"accuracy": acc, "f1": f1, "precision": precision, "recall": recall}

# Assuming you have already re-initialized your Trainer with the updated compute_metrics function

# 1. Run the evaluation
evaluation_results = trainer.evaluate()

# 2. Print the results (This is where the output is displayed)
print("--- Evaluation Metrics (3-Class Model) ---")
print(evaluation_results)